### ISSUE TITLE
Additional attributes in the entity

### ISSUE THREAD

**Issue by rgruebel** [custom-cards/check-button-card#1]
First, really nice card. Would it be possible to save the severity as an attribute in the entity? Also the title and an additional option "description" would be very useful as attributes for me. I want to use this information in an appdaeemon app

**Comment by Gluwc** [comment]
Apologies for the very late response. I already made some code for bar-card which allows you to store the config as an entity customization. I'll try to add this to the next release.

**Comment by Gluwc** [comment]
[1.0.0](https://github.com/custom-cards/check-button-card/releases/tag/1.0.0) now adds severity as an entity attribute. I've also added the `automation` config option so you can add any variables you want.
