### ISSUE TITLE
Feature Request: HACS

### ISSUE THREAD

**Issue by ChrisRomp** [custom-cards/check-button-card#16]
Would love to see this repo get added to [HACS](https://hacs.xyz/) for easier updates. I think it would increase usage, dramatically, also as this is a very useful card.

**Comment by jeremywillans** [comment]
... it’s in HACS?

**Comment by ChrisRomp** [comment]
> ... it’s in HACS?

Oops! It is. I did a quick search by clicking add, but didn't realize it was already added, so HACS filtered it out. Never mind. :)
