### ISSUE TITLE
Display specific amount of days instead of "1 week"

### ISSUE THREAD

**Issue by mammuth** [custom-cards/check-button-card#5]
I find your plugin pretty cool!

As far as I can see it, eg. 9 days are displayed as "1 week", right? Is there a way to have "9 days" being displayed as "9 days" in the card?

Right now many of my buttons are pretty fuzzy because of this 🤔

**Comment by Gluwc** [comment]
Apologies for the very late response. I was working on a more customizable time display a while ago, but had to stop working on this card for a while. I'll try to implement this for the next release.

**Comment by Gluwc** [comment]
This should noa be possible with the `display_limit` option in [1.0.0](https://github.com/custom-cards/check-button-card/releases/tag/1.0.0).
